In [2]:
import torch
from torch import nn
from d2l import torch as d2l

def corr2d(X, K):  #@save
    """计算二维互相关运算"""
    h, w = K.shape
    Y = torch.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1)) #（X.height - K.height + 1, X.width - K.width + 1）输出的高和宽
    for i in range(Y.shape[0]): #遍历输出的高
        for j in range(Y.shape[1]):
            Y[i, j] = (X[i:i + h, j:j + w] * K).sum()
    return Y #从上到下，从左到右逐一计算

In [3]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
corr2d(X, K)

tensor([[19., 25.],
        [37., 43.]])

In [4]:
conv2d = nn.Conv2d(1,1, kernel_size=(1, 2), bias=False)
conv2d.weight.data = K.reshape(1, 1, 2, 2) #卷积核的高，宽，通道数
Y = conv2d(X.reshape(1, 1, 3, 3)) #输入的高，宽，通道数

In [5]:
print(Y)

tensor([[[[19., 25.],
          [37., 43.]]]], grad_fn=<ConvolutionBackward0>)


In [7]:
# stride padding
def comp_conv2d(conv2d, X):
    X = X.reshape((1, 1) + X.shape) #（批量大小，通道数，高，宽）
    Y = conv2d(X)
    return Y.reshape(Y.shape[2:]) #（高，宽）

In [19]:
X=torch.rand(size=(8, 8))
conv2d = nn.Conv2d(1, 1, kernel_size=(3, 5), padding=(0, 1), stride=(3, 4))
Y=comp_conv2d(conv2d, X)

In [20]:
print(X)
print(Y)

tensor([[0.4886, 0.9322, 0.7167, 0.9859, 0.3362, 0.4980, 0.0841, 0.2530],
        [0.9710, 0.5888, 0.8921, 0.4683, 0.0407, 0.3727, 0.1005, 0.5852],
        [0.4181, 0.7822, 0.0849, 0.9169, 0.4085, 0.3835, 0.9782, 0.9514],
        [0.5929, 0.2444, 0.3885, 0.6394, 0.0654, 0.6565, 0.9735, 0.9859],
        [0.1376, 0.8296, 0.4578, 0.5740, 0.8749, 0.1076, 0.4331, 0.9350],
        [0.5475, 0.2869, 0.8886, 0.6267, 0.1306, 0.0289, 0.9106, 0.6675],
        [0.0622, 0.8005, 0.9999, 0.2144, 0.8292, 0.4676, 0.0227, 0.6951],
        [0.2728, 0.0349, 0.9928, 0.1783, 0.7515, 0.5426, 0.7423, 0.3603]])
tensor([[ 0.1945, -0.0754],
        [ 0.0813, -0.0431]], grad_fn=<ReshapeAliasBackward0>)
